name: Publish Docker Image

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  docker:
    name: Docker

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: |
          docker buildx build -t ghcr.io/ilharp/stipic:$(git rev-parse --abbrev-ref HEAD)-$(git rev-list --count HEAD) --push .
        shell: bash
